language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ferris3' ]; then cd .. && eval "mv $currentfolder generator-ferris3" && cd generator-ferris3; fi

